restaurant with food menus, user follow, send email with activation code/menus/urls.py
from django.conf.urls import url
from .views import (
    ItemListView,
    ItemDetailView,
    ItemCreateView,
    ItemUpdateView,
)

urlpatterns = [
    url(r'^$', ItemListView.as_view(), name='list'),
    url(r'^create/$', ItemCreateView.as_view(), name='create'),
    # url(r'^(?P<pk>\d+)/edit/$', ItemUpdateView.as_view(), name='update'),
    # url(r'^(?P<pk>\d+)/$', ItemDetailView.as_view(), name='detail'),
    url(r'^(?P<pk>\d+)/$', ItemUpdateView.as_view(), name='detail'),
]

restaurant with food menus, user follow, send email with activation code/restaurant_project/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic import TemplateView
from django.contrib.auth.views import LoginView, LogoutView
from menus.views import HomeView


from profiles.views import ProfileFollowToggle, RegisterView, activate_user_view

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', HomeView.as_view(), name='home'),

    url(r'^profile-follow/$', ProfileFollowToggle.as_view(), name='follow'),

    url(r'^register/$', RegisterView.as_view(), name='register'),
    url(r'^activate/(?P<code>[a-z0-9].*)/$', activate_user_view, name='activate'),

    url(r'^login/$', LoginView.as_view(), name='login'),
    url(r'^logout/$', LogoutView.as_view(), name='logout'),
    url(r'^restaurants/', include('restaurants.urls', namespace='restaurants')),
    url(r'^items/', include('menus.urls', namespace='menus')),
    url(r'^profiles/', include('profiles.urls', namespace='profiles')),
    url(r'^about/$', TemplateView.as_view(template_name='about.html'), name='about'),
    url(r'^contact/$', TemplateView.as_view(template_name='contact.html'), name='contact'),
]

restaurant with food menus, user follow, send email with activation code/templates/snippets/css.html
<!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

<!-- Optional theme -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

restaurant with food menus, user follow, send email with activation code/templates/snippets/form-snippet.html
{% if form.errors.non_field_errors %}
    {{ form.errors.non_field_errors }}
{% endif %}
<h1>{{ title }}</h1>
<form method="POST" action="">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="{{ title }}" class="btn btn-primary">
</form>

{% if form.instance %}
    <h1>{{ form.instance.name }}</h1>
{% endif %}

restaurant with food menus, user follow, send email with activation code/templates/snippets/js.html
<script src="http://code.jquery.com/jquery-3.2.1.min.js"></script>
<!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

restaurant with food menus, user follow, send email with activation code/templates/snippets/nav.html
<h1 class="text-center"><a href="{% url 'home' %}">OSAMA MOHAMED.COM</a></h1>
{#        {{ block.super }}#}


{% if request.user.is_authenticated %}
{#    <a href="{{ obj.get_absolute_url }}">Profile</a>#}
{#    <a href="{% url 'profiles:detail' %}">Profile</a>#}
    <a href="{% url 'home' %}">Home</a>
    | <a href="{% url 'profiles:detail' username=request.user.username %}">Profile</a>
    | <a href="{% url 'restaurants:list' %}">Restaurants</a>
{#    | <a href="{% url 'restaurants:create' %}">Create Restaurant</a>#}
    | <a href="{% url 'menus:list' %}">Menus</a>
{#    | <a href="{% url 'menus:create' %}">Create Item</a>#}
    | <a href="{% url 'logout' %}">Logout</a>
{% else %}
    <a href="{% url 'home' %}">Home</a>
    | <a href="{% url 'about' %}">About</a>
    | <a href="{% url 'contact' %}">Contact</a>
    | <a href="{% url 'register' %}">Register</a>
    | <a href="{% url 'login' %}">Login</a>
{% endif %}

restaurant with food menus, user follow, send email with activation code/templates/snippets/side_bar.html
<ul>
    <li>Item 1</li>
    <li>Item 2</li>
    <li>Item 3</li>
    <li>Item 4</li>
    <li>Item 5</li>
</ul>