blog with facebook comments, like & share/blog/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^posts/', include('posts.urls', namespace='posts')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog with facebook comments, like & share/posts/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^$', views.list, name='list'),
    url(r'^create/$', views.create, name='create'),
    # url(r'^(?P<id>\d+)/$', views.detail, name='detail'),
    url(r'^(?P<slug>[\w-]+)/$', views.detail, name='detail'),
    # url(r'^(?P<id>\d+)/edit/$', views.update, name='update'),
    url(r'^(?P<slug>[\w-]+)/edit/$', views.update, name='update'),
    # url(r'^(?P<id>\d+)/delete/$', views.delete, name='delete'),
    url(r'^(?P<slug>[\w-]+)/delete/$', views.delete, name='delete'),
]

blog with facebook comments, like & share/posts/models.py
from django.db import models
from django.core.urlresolvers import reverse
from django.db.models.signals import pre_save
from django.utils.text import slugify
from django.utils import timezone
from django.conf import settings


class PostManager(models.Manager):
    def active(self, *args, **kwargs):
        return super(PostManager, self).filter(draft=False).filter(publish__lte=timezone.now())


def upload_location(instance, filename):
    return '%s / %s' % (instance.id, filename)


# def upload_location(instance, filename):
#     filebase, extension = filename.split('.')
#     return '%s / %s.%s' % (instance.id, instance.id, extension)


class Post(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, default=1) #blank=True, null=True)
    title = models.CharField(max_length=250)
    slug = models.SlugField(unique=True)
    content = models.TextField()
    draft = models.BooleanField(default=False)
    publish = models.DateField(auto_now=False, auto_now_add=False)
    image = models.ImageField(#upload_to=upload_location,
                              null=True,
                              blank=True,
                              height_field='height_field',
                              width_field='width_field')
    height_field = models.IntegerField(default=0)
    width_field = models.IntegerField(default=0)
    added = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    objects = PostManager()
    # posts = PostManager()

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        # return reverse('posts:detail', kwargs={'id': self.id})
        return reverse('posts:detail', kwargs={'slug': self.slug})
        # return '/posts/%s/' %(self.id)

    class Meta:
        ordering = ['-id', '-added']


def create_slug(instance, new_slug=None):
    slug = slugify(instance.title)
    if new_slug is not None:
        slug = new_slug
    qs = Post.objects.filter(slug=slug).order_by('-id')
    exists = qs.exists()
    if exists:
        new_slug = '%s-%s' % (slug, qs.first().id)
        return create_slug(instance, new_slug=new_slug)
    return slug


def pre_save_post_reciver(sender, instance, *args, **kwargs):
    if not instance.slug:
        instance.slug = create_slug(instance)

# def pre_save_post_reciver(sender, instance, *args, **kwargs):
#     slug = slugify(instance.title)
#     exists = Post.objects.filter(slug=slug).exists()
#     if exists:
#         slug = '%s / %s ' % (slug, instance.id)
#     instance.slug = slug


pre_save.connect(pre_save_post_reciver, sender=Post)

blog with facebook comments, like & share/posts/forms.py
from django import forms
from .models import Post


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = [
            'title',
            'content',
            'image',
            'draft',
            'publish',
        ]

blog with facebook comments, like & share/posts/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse, HttpResponseRedirect, Http404
from django.contrib import messages
from django.utils import timezone
from django.db.models import Q
from .models import Post
from .forms import PostForm

from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger


def list(request):
    # queryset_list = Post.objects.filter(draft=False).filter(publish__lte=timezone.now())#.all() #.order_by('-id')
    # queryset_list = Post.objects.all()
    today = timezone.now().date()
    queryset_list = Post.objects.active()
    if request.user.is_staff or request.user.is_superuser:
        queryset_list = Post.objects.all()
    search_post = request.GET.get('search_post')
    if search_post:
        queryset_list = queryset_list.filter(
            Q(title__icontains=search_post) |
            Q(content__icontains=search_post) |
            Q(user__first_name__icontains=search_post) |
            Q(user__last_name__icontains=search_post)
        ).distinct()
    paginator = Paginator(queryset_list, 2)
    page_request = 'page'
    page = request.GET.get(page_request)
    try:
        queryset = paginator.page(page)
    except PageNotAnInteger:
        queryset = paginator.page(1)
    except EmptyPage:
        queryset = paginator.page(paginator.num_pages)
    context = {
        'objects': queryset,
        'page_request': page_request,
        'today': today
    }
    return render(request, 'index.html', context)


def create(request):
    if not request.user.is_staff or not request.user.is_superuser:
        raise Http404
    if not request.user.is_authenticated:
        raise Http404
    if request.method == 'POST':
        form = PostForm(request.POST or None, request.FILES or None)
        if form.is_valid():
            instance = form.save(commit=False)
            instance.user = request.user
            instance.save()
            messages.success(request, 'Successfully created!')
            return HttpResponseRedirect(instance.get_absolute_url())
    else:
        form = PostForm()
        # messages.error(request, 'Not successfully created!')
    context = {
        'form': form,
    }
    return render(request, 'form.html', context)


# def detail(request, id):
def detail(request, slug):
    # queryset = get_object_or_404(Post, id=id)
    queryset = get_object_or_404(Post, slug=slug)
    if queryset.draft or queryset.publish > timezone.now().date():
        if not request.user.is_staff or request.user.is_superuser:
            raise Http404
    context = {
        'title': queryset.title,
        'obj': queryset,
    }
    return render(request, 'detail.html', context)


# def update(request, id):
def update(request, slug):
    if not request.user.is_staff or not request.user.is_superuser:
        raise Http404
    if not request.user.is_authenticated:
        raise Http404
    # queryset = get_object_or_404(Post, id=id)
    queryset = get_object_or_404(Post, slug=slug)
    # if request.method == 'POST':
    form = PostForm(request.POST or None, request.FILES or None, instance=queryset)
    if form.is_valid():
        instance = form.save(commit=False)
        instance.save()
        messages.success(request, 'Successfully saved!')
        # messages.success(request, '<a href="#" >Successfully saved!</a>', extra_tags='osama mohamed html_safe')
        # messages.success(request, 'Successfully saved too!')
        return HttpResponseRedirect(instance.get_absolute_url())
    # else:
    #     form = PostForm(instance=queryset)
    #     messages.error(request, 'Not successfully saved!')
    context = {
        'title': queryset.title,
        'obj': queryset,
        'form': form,
    }
    return render(request, 'form.html', context)


# def delete(request, id):
def delete(request, slug):
    if not request.user.is_staff or not request.user.is_superuser:
        raise Http404
    if not request.user.is_authenticated:
        raise Http404
    # instance = get_object_or_404(Post, id=id)
    instance = get_object_or_404(Post, slug=slug)
    instance.delete()
    messages.success(request, 'Successfully deleted!')
    return redirect('posts:list')

blog with facebook comments, like & share/templates/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>
            {% block title %}
                Home Page
            {% endblock %}
        </title>
        {% load static %}
        <!-- Latest compiled and minified CSS -->
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

        <!-- Optional theme -->
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
        <link rel="stylesheet" href="{% static 'css/base.css' %}">
    </head>
    <body>
        <div id="fb-root"></div>
        <script>(function(d, s, id) {
                var js, fjs = d.getElementsByTagName(s)[0];
                if (d.getElementById(id)) return;
                js = d.createElement(s); js.id = id;
                js.src = 'https://connect.facebook.net/en_US/sdk.js#xfbml=1&version=v2.11';
                fjs.parentNode.insertBefore(js, fjs);
                }(document, 'script', 'facebook-jssdk'));</script>

        {% include 'messages.html' %}
        <div class="container">
            {% block body %}

            {% endblock %}
        </div>

        <!-- Latest compiled and minified JavaScript -->
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
    </body>
</html>

blog with facebook comments, like & share/templates/detail.html
{% extends 'base.html' %}
{% block title %}
    {{ title }} Detail
{% endblock %}
{% block body %}
    <div class="col-sm-6 col-sm-offset-3">
        <br>
        <a href="{% url 'posts:list' %}" class="btn btn-primary">All Posts</a>
        <br>
        <br>
{#        <h1>{{ title }} Detail!</h1>#}
{#        <h1>{{ obj.id }}</h1>#}
        {% if obj.image %}
            <img src="{{ obj.image.url }}" class="img-responsive" alt="{{ obj.title }}" title="{{ obj.title }}">
        {% endif %}
        <h2>{{ obj.title }}
            {% if obj.draft %}
                <small><span style="color: red;">Draft</span> {{ obj.publish }}</small>
            {% else %}
                <small>{{ obj.added }}</small>
            {% endif %}
        </h2>
        <p>Added on : {{ obj.added }}</p>
        <p>Updated on : {{ obj.updated }}</p>
        <p>Published on : {{ obj.publish }}</p>
        <p>{{ obj.content | linebreaks }}</p>
        <p>Author : {{ obj.user }}</p>
        {% if obj.user.get_full_name %}
            <p>Author : {{ obj.user.get_full_name }}</p>
        {% endif %}
{#        <p>{{ obj.added }}</p>#}
{#        <p>{{ obj.updated }}</p>#}
        <p>URL : {{ request.build_absolute_uri }}</p>
        <a href="https://www.facebook.com/sharer/sharer.php?u={{ request.build_absolute_uri }}">
            Facebook
        </a>
        <br>
        <br>
        <div class="fb-like" data-href="{{ request.build_absolute_uri }}" data-layout="standard" data-action="like" data-size="small" data-show-faces="true" data-share="true"></div>
        <hr>
        <br>
        <div class="fb-comments" data-href="{{ request.build_absolute_uri }}" data-numposts="5"></div>
    </div>
{% endblock %}

blog with facebook comments, like & share/templates/form.html
{% extends 'base.html' %}
{% block title %}
    Create
{% endblock %}
{% block body %}
    <div class="col-sm-6 col-sm-offset-3">
        <div class="row">
            <div class="col-sm-12">
                <h1>Form</h1>
                <form method="post" action="" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <input type="submit" value="Create Post" class="btn btn-primary">
                </form>
            </div>
        </div>
    </div>
{% endblock %}

blog with facebook comments, like & share/templates/index.html
{% extends 'base.html' %}

{% block body %}
    <div class="col-sm-6 col-sm-offset-3">
    <h1>Posts!</h1>
    <a href="{% url 'posts:create' %}" class="btn btn-success" role="button">Create</a>
    <br>
    <br>
    <form method="get" action="">
        <input type="text" name="search_post" value="{{ request.GET.search_post }}" placeholder="Search Posts ...">
        <input type="submit" value="Search">
    </form>
    <br>
    <br>
    <div class="row">
    {% for obj in objects %}
      <div class="col-sm-12">
        <div class="thumbnail">
          {% if obj.image %}
            <img src="{{ obj.image.url }}" class="img-responsive" alt="{{ obj.title }}">
          {% endif %}
          <div class="caption">
            <h3>
                {% if obj.draft %}
                    Staff only : <span style="color: red;">Draft</span>
                {% endif %}
            </h3>
            <h3>
                {% if obj.publish > today %}
                    Staff only : <span style="color: red;">Future Post</span>
                {% endif %}
            </h3>
            <h3><a href="{{ obj.get_absolute_url }}">{{ obj.title }}</a> &emsp; <small>{{ obj.added | timesince}} ago</small></h3>
            {% if obj.user.get_full_name %}
                <p>Author : {{ obj.user.get_full_name }}</p>
            {% endif %}
            <p>Author : {{ obj.user }}</p>
            <p>{{ obj.content | linebreaks | truncatechars:85 }} </p>
            <p>
                <a href="{% url 'posts:detail' slug=obj.slug %}" class="btn btn-primary" role="button">View</a>
                <a href="{% url 'posts:update' slug=obj.slug %}" class="btn btn-success" role="button">Edit</a>
                <a href="{% url 'posts:delete' slug=obj.slug %}" class="btn btn-danger" role="button">Delete</a>
{#                <a href="{% url 'posts:detail' id=obj.id %}" class="btn btn-primary" role="button">View</a>#}
{#                <a href="{% url 'posts:update' id=obj.id %}" class="btn btn-success" role="button">Edit</a>#}
{#                <a href="{% url 'posts:delete' id=obj.id %}" class="btn btn-danger" role="button">Delete</a>#}
            </p>
          </div>
        </div>
      </div>
{#      {% cycle '' '<div class="col-sm-12"><hr></div></div><div class="row">' %}#}
    {% endfor %}

    <div class="pagination">
        <span class="step-links">
            {% if objects.has_previous %}
                <a href="?{{ page_request }}={{ objects.previous_page_number }}{% if request.GET.search_post %}&search_post={{ request.GET.search_post }}{% endif %}">previous</a>
            {% endif %}

            <span class="current">
                Page {{ objects.number }} of {{ objects.paginator.num_pages }}.
            </span>

            {% if objects.has_next %}
                <a href="?{{ page_request }}={{ objects.next_page_number }}{% if request.GET.search_post %}&search_post={{ request.GET.search_post }}{% endif %}">next</a>
            {% endif %}
        </span>
    </div>


    </div>
    </div>
{% endblock %}


{#        <h1>{{ obj.id }}</h1>#}
    {#            <h2><a href="{% url 'posts:detail' id=obj.id %}">{{ obj.title }}</a></h2>#}
{#        <h2><a href="{{ obj.get_absolute_url }}">{{ obj.title }}</a></h2>#}
{#        <p>{{ obj.content | linebreaks | truncatechars:120 }}</p>#}
{#        <p>{{ obj.added }}</p>#}
{#        <p>{{ obj.updated }}</p>#}
{#        <a href="{% url 'posts:update' id=obj.id %}">edit {{ obj.title }}</a>#}
{#        <a href="{% url 'posts:delete' id=obj.id %}">delete {{ obj.title }}</a>#}

blog with facebook comments, like & share/templates/messages.html
{% if messages %}
    <ul class="messages">
        {% for message in messages %}
            <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
            <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>
                {% if 'html_safe' in message.tags %}
                    {{ message | safe }}
                {% else %}
                    {{ message }}
                {% endif %}
            </li>
        {% endfor %}
    </ul>
{% endif %}