Blog_django/account/urls.py
from django.conf.urls import url
from django.contrib.auth.views import LoginView, LogoutView

from .views import (
    RegisterView,
)


urlpatterns = [
    url(r'^register/$', RegisterView.as_view(), name='register'),
    url(r'^login/$', LoginView.as_view(template_name='account/login.html'), name="login"),
    url(r'^logout/$', LogoutView.as_view(template_name='account/login.html'), name="logout"),
]

Blog_django/article/urls.py
from django.conf.urls import url

from .views import (
    AllArticlesListView,
    ArticleDetailView,
    ArticlesByCategoryListView,
)


urlpatterns = [
    url(r'^$', AllArticlesListView.as_view(), name='list'),
    url(r'^article/(?P<slug>[\w-]+)/$', ArticleDetailView.as_view(), name='detail'),
    url(r'^category/(?P<category>[a-zA-Z0-9].*)/$', ArticlesByCategoryListView.as_view(), name='category'),
]

Blog_django/blog/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic import TemplateView

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^articles/', include('article.urls', namespace='articles')),
    url(r'^accounts/', include('account.urls', namespace='accounts')),
    url(r'^comments/', include('comment.urls', namespace='comments')),
    url(r'^about_me/$', TemplateView.as_view(template_name='about_me.html'), name='about_me'),
    url(r'^$', TemplateView.as_view(template_name='home.html'), name='home'),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Blog_django/templates/includes/css.html
{% load static %}

<link rel="shortcut icon" href="{%  static 'i.ico' %}">
<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
<link rel="stylesheet" href="{% static 'css/fontawesome-all.min.css' %}">


<link rel="stylesheet" href="{% static 'css/style.css' %}">

Blog_django/templates/includes/form.html
{% load crispy_forms_tags %}
<form method="POST" enctype="multipart/form-data" action="" class="form-group">
    {% csrf_token %}
{#    {{ form.as_p }}#}
    {{ form | crispy }}
    <button type="submit" class="btn btn-primary">{{ title }}</button>
</form>

Blog_django/templates/includes/js.html
{% load static %}

<script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<script src="{% static 'js/comment_reply_button.js' %}"></script>

Blog_django/templates/includes/messages.html
{% if messages %}
    <ul class="messages">
        {% for message in messages %}
            <li{% if message.tags %} class="alert alert-{{ message.tags }}"{% endif %}>{{ message }}</li>
        {% endfor %}
    </ul>
{% endif %}

Blog_django/templates/includes/nav_bar.html
{% load static %}
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="{% url 'home' %}">
          OSAMA MOHAMED
{#          <img alt="Brand" src="{% static 'brand.png' %}">#}
      </a>
    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <form method="post" action="{% url 'articles:list' %}" class="navbar-form navbar-left">
            {% csrf_token %}
            <div class="form-group">
              <input type="text" name="search" value="{{ request.POST.search }}" class="form-control" placeholder="Search">
            </div>
            <button type="submit" class="btn btn-default">Search</button>
          </form>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li><a href="{% url 'home' %}">Home</a></li>
        <li><a href="{% url 'about_me' %}">About Me</a></li>
        <li><a href="{% url 'articles:list' %}">All Articles</a></li>
        <li class="dropdown">
          {% if request.user.is_authenticated %}
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Settings <span class="caret"></span></a>
          {% else %}
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Register/Login <span class="caret"></span></a>
          {% endif %}
          <ul class="dropdown-menu">
            {% if request.user.is_authenticated %}
                <li><a href="{% url 'accounts:logout' %}">Logout</a></li>
            {% else %}
                <li><a href="{% url 'accounts:register' %}">Register</a></li>
                <li><a href="{% url 'accounts:login' %}">Login</a></li>
            {% endif %}
          </ul>
        </li>
      </ul>
    </div>
  </div>
</nav>